[package]
name = "tss-parallel"
description = "parallel.* native bindings"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tsr-realm.workspace = true
tsr-memory.workspace = true
tsr-scheduler.workspace = true
tsr-task.workspace = true
tsr-io.workspace = true
tsr-channel.workspace = true
tsr-gc.workspace = true
