[package]
name = "tsr-io"
description = "Native I/O: console, time (event loop is M2+)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tsr-realm.workspace = true
crossbeam-channel.workspace = true
libc.workspace = true
tsr-memory.workspace = true
tsr-task.workspace = true
