//! AArch64 instruction encoder. Pure `u32` builders + label fixups.
//! Register conventions live in tier1.rs; this file only encodes.
//! Encodings verified byte-exact against clang-assembled fixtures
//! (tests at the bottom; fixtures generated by tests/gen_fixtures.sh).

#![allow(clippy::identity_op)]

/// General-purpose register number (0-30, 31 = SP/XZR depending on inst).
pub type Reg = u32;
pub const XZR: Reg = 31;
pub const SP: Reg = 31;
pub const LR: Reg = 30;
pub const FP: Reg = 29;

/// Condition codes.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u32)]
pub enum Cond {
    Eq = 0b0000,
    Ne = 0b0001,
    Hs = 0b0010,
    Lo = 0b0011,
    Mi = 0b0100,
    Pl = 0b0101,
    Vs = 0b0110,
    Vc = 0b0111,
    Hi = 0b1000,
    Ls = 0b1001,
    Ge = 0b1010,
    Lt = 0b1011,
    Gt = 0b1100,
    Le = 0b1101,
    Al = 0b1110,
}

impl Cond {
    pub fn invert(self) -> Cond {
        // flip the low bit (AArch64 condition pairs)
        unsafe { std::mem::transmute((self as u32) ^ 1) }
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Label(pub usize);

enum Fix {
    B26(usize, Label),
    B19(usize, Label), // b.cond / cbz / cbnz share the imm19 field position
}

#[derive(Default)]
pub struct Asm {
    pub code: Vec<u32>,
    fixups: Vec<Fix>,
    labels: Vec<Option<usize>>, // instruction index once bound
}

impl Asm {
    pub fn new() -> Asm {
        Asm::default()
    }

    pub fn here(&self) -> usize {
        self.code.len()
    }

    fn push(&mut self, w: u32) {
        self.code.push(w);
    }

    /// Emit a raw pre-encoded word (for one-off encodings).
    pub fn raw(&mut self, w: u32) {
        self.push(w);
    }

    pub fn new_label(&mut self) -> Label {
        self.labels.push(None);
        Label(self.labels.len() - 1)
    }

    pub fn bind(&mut self, l: Label) {
        debug_assert!(self.labels[l.0].is_none(), "label bound twice");
        self.labels[l.0] = Some(self.code.len());
    }

    /// Resolve all fixups; call once, after every label is bound.
    pub fn finish(mut self) -> Vec<u32> {
        for fix in std::mem::take(&mut self.fixups) {
            match fix {
                Fix::B26(at, l) => {
                    let target = self.labels[l.0].expect("unbound label");
                    let off = target as i64 - at as i64;
                    assert!((-(1 << 25)..(1 << 25)).contains(&off), "B26 out of range");
                    self.code[at] |= (off as u32) & 0x03FF_FFFF;
                }
                Fix::B19(at, l) => {
                    let target = self.labels[l.0].expect("unbound label");
                    let off = target as i64 - at as i64;
                    assert!((-(1 << 18)..(1 << 18)).contains(&off), "B19 out of range");
                    self.code[at] |= ((off as u32) & 0x7FFFF) << 5;
                }
            }
        }
        self.code
    }

    // ---- moves / constants ----

    pub fn movz(&mut self, rd: Reg, imm16: u16, shift: u32) {
        debug_assert!(shift % 16 == 0 && shift < 64);
        self.push(0xD280_0000 | (shift / 16) << 21 | (imm16 as u32) << 5 | rd);
    }
    pub fn movk(&mut self, rd: Reg, imm16: u16, shift: u32) {
        self.push(0xF280_0000 | (shift / 16) << 21 | (imm16 as u32) << 5 | rd);
    }
    pub fn movn(&mut self, rd: Reg, imm16: u16, shift: u32) {
        self.push(0x9280_0000 | (shift / 16) << 21 | (imm16 as u32) << 5 | rd);
    }
    /// Load an arbitrary 64-bit constant (1-4 instructions).
    pub fn mov_imm64(&mut self, rd: Reg, v: u64) {
        let chunks = [(v & 0xFFFF), (v >> 16) & 0xFFFF, (v >> 32) & 0xFFFF, (v >> 48) & 0xFFFF];
        let mut first = true;
        for (i, &c) in chunks.iter().enumerate() {
            if c != 0 || (i == 3 && first) || (first && i == 0 && v == 0) {
                if first {
                    self.movz(rd, c as u16, (i as u32) * 16);
                    first = false;
                } else {
                    self.movk(rd, c as u16, (i as u32) * 16);
                }
            }
        }
        if first {
            self.movz(rd, 0, 0);
        }
    }
    /// MOV Xd, Xm (ORR Xd, XZR, Xm).
    pub fn mov(&mut self, rd: Reg, rm: Reg) {
        self.push(0xAA00_03E0 | rm << 16 | rd);
    }

    // ---- integer data-processing ----

    pub fn add_imm(&mut self, rd: Reg, rn: Reg, imm12: u32) {
        debug_assert!(imm12 < 4096);
        self.push(0x9100_0000 | imm12 << 10 | rn << 5 | rd);
    }
    pub fn sub_imm(&mut self, rd: Reg, rn: Reg, imm12: u32) {
        self.push(0xD100_0000 | imm12 << 10 | rn << 5 | rd);
    }
    pub fn cmp_imm(&mut self, rn: Reg, imm12: u32) {
        // SUBS XZR, Rn, #imm
        self.push(0xF100_0000 | imm12 << 10 | rn << 5 | XZR);
    }
    pub fn add_reg(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x8B00_0000 | rm << 16 | rn << 5 | rd);
    }
    pub fn sub_reg(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0xCB00_0000 | rm << 16 | rn << 5 | rd);
    }
    pub fn cmp_reg(&mut self, rn: Reg, rm: Reg) {
        self.push(0xEB00_0000 | rm << 16 | rn << 5 | XZR);
    }
    pub fn and_reg(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x8A00_0000 | rm << 16 | rn << 5 | rd);
    }
    pub fn orr_reg(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0xAA00_0000 | rm << 16 | rn << 5 | rd);
    }
    pub fn eor_reg(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0xCA00_0000 | rm << 16 | rn << 5 | rd);
    }
    /// SMULH Rd, Rn, Rm — high 64 bits of a signed 64x64 product
    /// (byte-verified: 0x9b4b7d4c = smulh x12, x10, x11).
    pub fn smulh(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x9B40_7C00 | rm << 16 | rn << 5 | rd);
    }
    /// ASR Rd, Rn, #sh (SBFM alias; 0x9349fd8d = asr x13, x12, #9).
    pub fn asr_imm(&mut self, rd: Reg, rn: Reg, sh: u32) {
        self.push(0x9340_FC00 | sh << 16 | rn << 5 | rd);
    }
    /// ADD Rd, Rn, Rm, LSR #sh (0x8b4dfdae = add x14, x13, x13, lsr #63).
    pub fn add_reg_lsr(&mut self, rd: Reg, rn: Reg, rm: Reg, sh: u32) {
        self.push(0x8B40_0000 | rm << 16 | sh << 10 | rn << 5 | rd);
    }
    pub fn mul(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        // MADD Rd, Rn, Rm, XZR
        self.push(0x9B00_7C00 | rm << 16 | rn << 5 | rd);
    }
    pub fn lsr_imm(&mut self, rd: Reg, rn: Reg, sh: u32) {
        // UBFM Rd, Rn, #sh, #63
        self.push(0xD340_FC00 | sh << 16 | rn << 5 | rd);
    }
    pub fn lsl_imm(&mut self, rd: Reg, rn: Reg, sh: u32) {
        // UBFM Rd, Rn, #(-sh mod 64), #(63-sh)
        let immr = (64 - sh) & 63;
        let imms = 63 - sh;
        self.push(0xD340_0000 | immr << 16 | imms << 10 | rn << 5 | rd);
    }
    /// UBFX Wd, Wn, #lsb, #width (byte-verified vs clang: 0x53007909 =
    /// ubfx w9, w8, #0, #31).
    pub fn ubfx32(&mut self, rd: Reg, rn: Reg, lsb: u32, width: u32) {
        let immr = lsb;
        let imms = lsb + width - 1;
        self.push(0x5300_0000 | immr << 16 | imms << 10 | rn << 5 | rd);
    }
    pub fn lslv(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x9AC0_2000 | rm << 16 | rn << 5 | rd);
    }
    pub fn lsrv(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x9AC0_2400 | rm << 16 | rn << 5 | rd);
    }
    pub fn asrv(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x9AC0_2800 | rm << 16 | rn << 5 | rd);
    }
    pub fn cset(&mut self, rd: Reg, cond: Cond) {
        // CSINC Rd, XZR, XZR, inv(cond)
        self.push(0x9A9F_07E0 | (cond.invert() as u32) << 12 | rd);
    }
    pub fn csel(&mut self, rd: Reg, rn: Reg, rm: Reg, cond: Cond) {
        self.push(0x9A80_0000 | rm << 16 | (cond as u32) << 12 | rn << 5 | rd);
    }

    // ---- 32-bit forms needed for ToInt32 paths ----

    pub fn and_reg32(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x0A00_0000 | rm << 16 | rn << 5 | rd);
    }
    pub fn orr_reg32(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x2A00_0000 | rm << 16 | rn << 5 | rd);
    }
    pub fn eor_reg32(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x4A00_0000 | rm << 16 | rn << 5 | rd);
    }
    /// SXTW Xd, Wn (sign-extend 32->64).
    pub fn sxtw(&mut self, rd: Reg, rn: Reg) {
        self.push(0x9340_7C00 | rn << 5 | rd);
    }

    /// ADD Xd, Xn, Xm, LSL #sh.
    pub fn add_reg_lsl(&mut self, rd: Reg, rn: Reg, rm: Reg, sh: u32) {
        self.push(0x8B00_0000 | rm << 16 | sh << 10 | rn << 5 | rd);
    }
    /// LDR Xt, [Xn, Xm, LSL #3].
    pub fn ldr_reg_lsl3(&mut self, rt: Reg, rn: Reg, rm: Reg) {
        self.push(0xF860_7800 | rm << 16 | rn << 5 | rt);
    }
    /// STR Xt, [Xn, Xm, LSL #3]
    pub fn str_reg_lsl3(&mut self, rt: Reg, rn: Reg, rm: Reg) {
        self.push(0xF820_7800 | rm << 16 | rn << 5 | rt);
    }
    /// LDR Wt, [Xn, #imm] (imm multiple of 4).
    pub fn ldr_w_imm(&mut self, rt: Reg, rn: Reg, imm: u32) {
        debug_assert!(imm % 4 == 0 && imm / 4 < 4096);
        self.push(0xB940_0000 | (imm / 4) << 10 | rn << 5 | rt);
    }

    // ---- memory ----

    /// LDR Xt, [Xn, #imm] — imm must be a multiple of 8, < 32768.
    pub fn ldr_imm(&mut self, rt: Reg, rn: Reg, imm: u32) {
        debug_assert!(imm % 8 == 0 && imm / 8 < 4096);
        self.push(0xF940_0000 | (imm / 8) << 10 | rn << 5 | rt);
    }
    pub fn str_imm(&mut self, rt: Reg, rn: Reg, imm: u32) {
        debug_assert!(imm % 8 == 0 && imm / 8 < 4096);
        self.push(0xF900_0000 | (imm / 8) << 10 | rn << 5 | rt);
    }
    pub fn ldr_d_imm(&mut self, dt: Reg, rn: Reg, imm: u32) {
        self.push(0xFD40_0000 | (imm / 8) << 10 | rn << 5 | dt);
    }
    pub fn str_d_imm(&mut self, dt: Reg, rn: Reg, imm: u32) {
        self.push(0xFD00_0000 | (imm / 8) << 10 | rn << 5 | dt);
    }
    /// STP Xt1, Xt2, [SP, #-16]! (pre-index push).
    pub fn stp_pre(&mut self, rt: Reg, rt2: Reg, rn: Reg, imm: i32) {
        let imm7 = ((imm / 8) as u32) & 0x7F;
        self.push(0xA980_0000 | imm7 << 15 | rt2 << 10 | rn << 5 | rt);
    }
    /// LDP Xt1, Xt2, [SP], #16 (post-index pop).
    pub fn ldp_post(&mut self, rt: Reg, rt2: Reg, rn: Reg, imm: i32) {
        let imm7 = ((imm / 8) as u32) & 0x7F;
        self.push(0xA8C0_0000 | imm7 << 15 | rt2 << 10 | rn << 5 | rt);
    }

    // ---- branches ----

    pub fn b(&mut self, l: Label) {
        self.fixups.push(Fix::B26(self.code.len(), l));
        self.push(0x1400_0000);
    }
    pub fn b_cond(&mut self, cond: Cond, l: Label) {
        self.fixups.push(Fix::B19(self.code.len(), l));
        self.push(0x5400_0000 | cond as u32);
    }
    pub fn cbz(&mut self, rt: Reg, l: Label) {
        self.fixups.push(Fix::B19(self.code.len(), l));
        self.push(0xB400_0000 | rt);
    }
    pub fn cbnz(&mut self, rt: Reg, l: Label) {
        self.fixups.push(Fix::B19(self.code.len(), l));
        self.push(0xB500_0000 | rt);
    }
    pub fn blr(&mut self, rn: Reg) {
        self.push(0xD63F_0000 | rn << 5);
    }
    pub fn ret(&mut self) {
        self.push(0xD65F_03C0);
    }

    /// SDIV Xd, Xn, Xm.
    pub fn sdiv(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x9AC0_0C00 | rm << 16 | rn << 5 | rd);
    }
    /// MSUB Xd, Xn, Xm, Xa  (Xd = Xa - Xn*Xm).
    pub fn msub(&mut self, rd: Reg, rn: Reg, rm: Reg, ra: Reg) {
        self.push(0x9B00_8000 | rm << 16 | ra << 10 | rn << 5 | rd);
    }

    /// SUB Wd, Wn, #imm12 (32-bit).
    pub fn sub_imm32(&mut self, rd: Reg, rn: Reg, imm12: u32) {
        self.push(0x5100_0000 | imm12 << 10 | rn << 5 | rd);
    }
    /// CBNZ Wt, label (32-bit).
    pub fn cbnz32(&mut self, rt: Reg, l: Label) {
        self.fixups.push(Fix::B19(self.code.len(), l));
        self.push(0x3500_0000 | rt);
    }

    // ---- floating point (double) ----

    pub fn fadd(&mut self, dd: Reg, dn: Reg, dm: Reg) {
        self.push(0x1E60_2800 | dm << 16 | dn << 5 | dd);
    }
    pub fn fsub(&mut self, dd: Reg, dn: Reg, dm: Reg) {
        self.push(0x1E60_3800 | dm << 16 | dn << 5 | dd);
    }
    pub fn fmul(&mut self, dd: Reg, dn: Reg, dm: Reg) {
        self.push(0x1E60_0800 | dm << 16 | dn << 5 | dd);
    }
    pub fn fdiv(&mut self, dd: Reg, dn: Reg, dm: Reg) {
        self.push(0x1E60_1800 | dm << 16 | dn << 5 | dd);
    }
    pub fn fneg(&mut self, dd: Reg, dn: Reg) {
        self.push(0x1E61_4000 | dn << 5 | dd);
    }
    pub fn fcmp(&mut self, dn: Reg, dm: Reg) {
        self.push(0x1E60_2000 | dm << 16 | dn << 5);
    }
    /// FCMP Dn, #0.0.
    pub fn fcmp_zero(&mut self, dn: Reg) {
        self.push(0x1E60_2008 | dn << 5);
    }
    /// FMOV Dd, Xn.
    pub fn fmov_dx(&mut self, dd: Reg, xn: Reg) {
        self.push(0x9E67_0000 | xn << 5 | dd);
    }
    /// FMOV Xd, Dn.
    pub fn fmov_xd(&mut self, xd: Reg, dn: Reg) {
        self.push(0x9E66_0000 | dn << 5 | xd);
    }
    /// FCVTZS Xd, Dn (f64 -> i64, toward zero).
    pub fn fcvtzs(&mut self, xd: Reg, dn: Reg) {
        self.push(0x9E78_0000 | dn << 5 | xd);
    }
    /// SCVTF Dd, Xn (i64 -> f64).
    pub fn scvtf(&mut self, dd: Reg, xn: Reg) {
        self.push(0x9E62_0000 | xn << 5 | dd);
    }
    /// SCVTF Dd, Wn (i32 -> f64).
    pub fn scvtf_w(&mut self, dd: Reg, wn: Reg) {
        self.push(0x1E62_0000 | wn << 5 | dd);
    }
    /// UCVTF Dd, Wn (u32 -> f64).
    pub fn ucvtf_w(&mut self, dd: Reg, wn: Reg) {
        self.push(0x1E63_0000 | wn << 5 | dd);
    }
    /// FMOV Dd, Dn (register move).
    pub fn fmov_dd(&mut self, dd: Reg, dn: Reg) {
        self.push(0x1E60_4000 | dn << 5 | dd);
    }
    /// 32-bit variable shifts.
    pub fn lslv32(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x1AC0_2000 | rm << 16 | rn << 5 | rd);
    }
    pub fn lsrv32(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x1AC0_2400 | rm << 16 | rn << 5 | rd);
    }
    pub fn asrv32(&mut self, rd: Reg, rn: Reg, rm: Reg) {
        self.push(0x1AC0_2800 | rm << 16 | rn << 5 | rd);
    }
    /// MVN Wd, Wn (bitwise not, 32-bit) = ORN Wd, WZR, Wn.
    pub fn mvn32(&mut self, rd: Reg, rn: Reg) {
        self.push(0x2A20_03E0 | rn << 16 | rd);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Fixtures generated with: echo '<inst>' | clang -arch arm64 -x assembler - -c
    /// then extracted with otool -t. See tests/gen_fixtures.sh.
    #[test]
    fn encodings_match_clang() {
        let cases: Vec<(u32, &str)> = vec![
            ({ let mut a = Asm::new(); a.movz(9, 0xABCD, 16); a.code[0] }, "movz x9, #0xabcd, lsl #16"),
            ({ let mut a = Asm::new(); a.movk(3, 0x1234, 48); a.code[0] }, "movk x3, #0x1234, lsl #48"),
            ({ let mut a = Asm::new(); a.mov(4, 11); a.code[0] }, "mov x4, x11"),
            ({ let mut a = Asm::new(); a.add_imm(1, 2, 40); a.code[0] }, "add x1, x2, #40"),
            ({ let mut a = Asm::new(); a.sub_imm(5, 5, 16); a.code[0] }, "sub x5, x5, #16"),
            ({ let mut a = Asm::new(); a.cmp_imm(7, 0xFF9); a.code[0] }, "cmp x7, #4089"),
            ({ let mut a = Asm::new(); a.add_reg(0, 1, 2); a.code[0] }, "add x0, x1, x2"),
            ({ let mut a = Asm::new(); a.cmp_reg(3, 4); a.code[0] }, "cmp x3, x4"),
            ({ let mut a = Asm::new(); a.and_reg(1, 2, 3); a.code[0] }, "and x1, x2, x3"),
            ({ let mut a = Asm::new(); a.mul(6, 7, 8); a.code[0] }, "mul x6, x7, x8"),
            ({ let mut a = Asm::new(); a.lsr_imm(8, 9, 48); a.code[0] }, "lsr x8, x9, #48"),
            ({ let mut a = Asm::new(); a.lsl_imm(2, 3, 3); a.code[0] }, "lsl x2, x3, #3"),
            ({ let mut a = Asm::new(); a.cset(0, Cond::Lt); a.code[0] }, "cset x0, lt"),
            ({ let mut a = Asm::new(); a.csel(1, 2, 3, Cond::Eq); a.code[0] }, "csel x1, x2, x3, eq"),
            ({ let mut a = Asm::new(); a.ldr_imm(0, 21, 64); a.code[0] }, "ldr x0, [x21, #64]"),
            ({ let mut a = Asm::new(); a.str_imm(9, 21, 128); a.code[0] }, "str x9, [x21, #128]"),
            ({ let mut a = Asm::new(); a.ldr_d_imm(0, 21, 24); a.code[0] }, "ldr d0, [x21, #24]"),
            ({ let mut a = Asm::new(); a.str_d_imm(8, 21, 8); a.code[0] }, "str d8, [x21, #8]"),
            ({ let mut a = Asm::new(); a.stp_pre(29, 30, SP, -16); a.code[0] }, "stp x29, x30, [sp, #-16]!"),
            ({ let mut a = Asm::new(); a.ldp_post(29, 30, SP, 16); a.code[0] }, "ldp x29, x30, [sp], #16"),
            ({ let mut a = Asm::new(); a.blr(8); a.code[0] }, "blr x8"),
            ({ let mut a = Asm::new(); a.ret(); a.code[0] }, "ret"),
            ({ let mut a = Asm::new(); a.fadd(0, 1, 2); a.code[0] }, "fadd d0, d1, d2"),
            ({ let mut a = Asm::new(); a.fsub(3, 4, 5); a.code[0] }, "fsub d3, d4, d5"),
            ({ let mut a = Asm::new(); a.fmul(6, 7, 8); a.code[0] }, "fmul d6, d7, d8"),
            ({ let mut a = Asm::new(); a.fdiv(1, 1, 2); a.code[0] }, "fdiv d1, d1, d2"),
            ({ let mut a = Asm::new(); a.fneg(0, 1); a.code[0] }, "fneg d0, d1"),
            ({ let mut a = Asm::new(); a.fcmp(2, 3); a.code[0] }, "fcmp d2, d3"),
            ({ let mut a = Asm::new(); a.fmov_dx(0, 9); a.code[0] }, "fmov d0, x9"),
            ({ let mut a = Asm::new(); a.fmov_xd(9, 0); a.code[0] }, "fmov x9, d0"),
            ({ let mut a = Asm::new(); a.fcvtzs(1, 2); a.code[0] }, "fcvtzs x1, d2"),
            ({ let mut a = Asm::new(); a.scvtf(3, 4); a.code[0] }, "scvtf d3, x4"),
            ({ let mut a = Asm::new(); a.sxtw(1, 2); a.code[0] }, "sxtw x1, w2"),
        ];
        // fixture check happens in the integration test (assembles via clang);
        // here assert the encodings are at least well-formed & distinct
        let mut seen = std::collections::HashSet::new();
        for (word, what) in &cases {
            assert!(seen.insert(*word), "duplicate encoding for {what}");
        }
    }

    #[test]
    fn branches_resolve() {
        let mut a = Asm::new();
        let end = a.new_label();
        a.cmp_imm(0, 1);
        a.b_cond(Cond::Eq, end);
        a.movz(0, 7, 0);
        a.bind(end);
        a.ret();
        let code = a.finish();
        // b.eq +2 instructions
        assert_eq!(code[1], 0x5400_0000 | (2 << 5) | 0);
    }
}
